title: Tree
author: Nguyễn Hữu Thành
version: 1.0
date: 20/10/2010
access: [administrators, developers]
category:
    name: section.system
    icon: images/tree.png
actions:
    createTreeType:
        title: Create a new Tree Type
        icon: images/scan_module.png
        menu:
            position: 1
        
            
    