<?php

/**
 * BaseWfWorkitem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $wf_id
 * @property integer $case_id
 * @property integer $transition_id
 * @property integer $transition_trigger
 * @property string $task_id
 * @property string $context
 * @property integer $workitem_status
 * @property timestamp $enabled_date
 * @property timestamp $cancelled_date
 * @property timestamp $finished_date
 * @property timestamp $deadline
 * @property integer $role_id
 * @property integer $user_id
 * @property WfWorkflow $WfWorkflow
 * @property WfTransition $WfTransition
 * @property WfCase $WfCase
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseWfWorkitem extends izDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wf_workitem');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('wf_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('case_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('transition_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('transition_trigger', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('task_id', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('context', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('workitem_status', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('enabled_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('cancelled_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('finished_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('deadline', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WfWorkflow', array(
             'local' => 'wf_id',
             'foreign' => 'id'));

        $this->hasOne('WfTransition', array(
             'local' => 'transition_id',
             'foreign' => 'id'));

        $this->hasOne('WfCase', array(
             'local' => 'case_id',
             'foreign' => 'id'));
    }
}