<?php

/**
 * BaseWfCase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $wf_id
 * @property string $context
 * @property integer $case_status
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property timestamp $created_date
 * @property integer $created_user
 * @property timestamp $revised_date
 * @property integer $revised_user
 * @property WfWorkflow $WfWorkflow
 * @property Doctrine_Collection $WfTokens
 * @property Doctrine_Collection $WfWorkitems
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseWfCase extends izDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wf_case');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('wf_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('context', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('case_status', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('created_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('created_user', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('revised_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('revised_user', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WfWorkflow', array(
             'local' => 'wf_id',
             'foreign' => 'id'));

        $this->hasMany('WfToken as WfTokens', array(
             'local' => 'id',
             'foreign' => 'case_id'));

        $this->hasMany('WfWorkitem as WfWorkitems', array(
             'local' => 'id',
             'foreign' => 'case_id'));
    }
}