<?php

/**
 * BaseWfTransition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $wf_id
 * @property string $transition_name
 * @property string $transition_desc
 * @property integer $transition_trigger
 * @property integer $time_limit
 * @property integer $task_id
 * @property integer $role_id
 * @property timestamp $created_date
 * @property integer $created_user
 * @property timestamp $revised_date
 * @property integer $revised_user
 * @property WfWorkflow $WfWorkflow
 * @property Doctrine_Collection $WfArcs
 * @property Doctrine_Collection $WfWorkitem
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseWfTransition extends izDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wf_transition');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('wf_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('transition_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('transition_desc', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('transition_trigger', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('time_limit', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('task_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('created_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('created_user', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('revised_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('revised_user', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WfWorkflow', array(
             'local' => 'wf_id',
             'foreign' => 'id'));

        $this->hasMany('WfArc as WfArcs', array(
             'local' => 'id',
             'foreign' => 'transition_id'));

        $this->hasMany('WfWorkitem', array(
             'local' => 'id',
             'foreign' => 'transition_id'));
    }
}