module: article
actions:
    createArticle:
        default:
            title: Add a new Article
            params: 
                - Category ID
            context:
                
                
    viewArticle:
        default      
                