<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityBaseActionDefinitionProxy extends \Entity\Base\ActionDefinition implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function __set($var, $val)
    {
        $this->__load();
        return parent::__set($var, $val);
    }

    public function __get($var)
    {
        $this->__load();
        return parent::__get($var);
    }

    public function assign($association, $collection)
    {
        $this->__load();
        return parent::assign($association, $collection);
    }

    public function addModule($module)
    {
        $this->__load();
        return parent::addModule($module);
    }

    public function getActions()
    {
        $this->__load();
        return parent::getActions();
    }

    public function getModule()
    {
        $this->__load();
        return parent::getModule();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'method', 'setting', 'is_widget', 'cached_duration', 'module', 'actions');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}