<?php

/**
 * BasePermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $guuid
 * @property string $name
 * @property Doctrine_Collection $Account
 * @property Doctrine_Collection $Role
 * @property Doctrine_Collection $RolePermission
 * @property Doctrine_Collection $AccountPermission
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePermission extends izDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('permission');
        $this->hasColumn('guuid', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Account', array(
             'refClass' => 'AccountPermission',
             'local' => 'permission_id',
             'foreign' => 'account_id'));

        $this->hasMany('Role', array(
             'refClass' => 'RolePermission',
             'local' => 'permission_id',
             'foreign' => 'role_id'));

        $this->hasMany('RolePermission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $this->hasMany('AccountPermission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));
    }
}