<?php

/**
 * BaseRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $guuid
 * @property string $name
 * @property Doctrine_Collection $Permission
 * @property Doctrine_Collection $Account
 * @property Doctrine_Collection $RolePermission
 * @property Doctrine_Collection $AccountRole
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRole extends izDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role');
        $this->hasColumn('guuid', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Permission', array(
             'refClass' => 'RolePermission',
             'local' => 'role_id',
             'foreign' => 'permission_id'));

        $this->hasMany('Account', array(
             'refClass' => 'AccountRole',
             'local' => 'role_id',
             'foreign' => 'account_id'));

        $this->hasMany('RolePermission', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $this->hasMany('AccountRole', array(
             'local' => 'id',
             'foreign' => 'role_id'));
    }
}